<script setup>
import { computed,ref } from 'vue';
import { ElMessage,ElMessageBox } from 'element-plus';
import { useUserStore } from '../stores/user.js';
import { useRefresh } from '../composables/useRefresh.js';
import api,{messageOf} from '../api/request.js';
const props=defineProps({courseId:[String,Number],readonly:Boolean});
const teacher=computed(()=>useUserStore().user?.role==='teacher'),tab=ref('private'),keyword=ref(''),filter=ref(''),page=ref(1),rows=ref([]),detail=ref(null),dialog=ref(false),compose=ref(false),editId=ref(null),title=ref(''),content=ref(''),mustPrivate=ref(true),reply=ref(''),publication=ref(false),summary=ref(''),publicReply=ref('');
async function load(){try{rows.value=(await api.get('/courses/'+props.courseId+'/questions'+(tab.value==='public'?'/public':''),{params:{keyword:keyword.value,status:filter.value,page:page.value,limit:20}})).data;}catch(e){ElMessage.error(messageOf(e));}}
async function open(row){try{detail.value=(await api.get('/questions/'+row.id)).data;reply.value='';dialog.value=true;}catch(e){ElMessage.error(messageOf(e));}}
function newQuestion(row=null){editId.value=row?.id||null;title.value=row?.title||'';content.value=row?.content||'';mustPrivate.value=true;compose.value=true;}
async function save(){try{if(editId.value)await api.put('/questions/'+editId.value,{title:title.value,content:content.value});else await api.post('/courses/'+props.courseId+'/questions',{title:title.value,content:content.value,must_private:mustPrivate.value});compose.value=false;await load();if(detail.value&&editId.value)await open(detail.value);}catch(e){ElMessage.error(messageOf(e));}}
async function action(url,body={},method='post'){try{await api[method]('/questions/'+detail.value.id+url,body);await open(detail.value);await load();ElMessage.success('已保存');return true;}catch(e){ElMessage.error(messageOf(e));return false;}}
async function sendReply(){if(await action('/replies',{content:reply.value}))reply.value='';}
async function privacy(){await action('/privacy',{must_private:!detail.value.must_private},'put');}
async function remove(){try{await ElMessageBox.confirm('确定删除尚未得到回复的问题？','确认');await api.delete('/questions/'+detail.value.id);dialog.value=false;await load();}catch(e){if(e!=='cancel')ElMessage.error(messageOf(e));}}
function publishDialog(){summary.value='';publicReply.value='';publication.value=true;}
async function publish(){if(await action('/publish',{summary:summary.value,reply:publicReply.value}))publication.value=false;}
function switchTab(){page.value=1;filter.value='';load();}
useRefresh(load);
</script>
<template><section>
<div class="toolbar"><el-radio-group v-model="tab" @change="switchTab"><el-radio-button value="private">{{teacher?'私人问题管理':'我的私人问题'}}</el-radio-button><el-radio-button value="public">全班公开问答</el-radio-button></el-radio-group><el-button v-if="!teacher&&!readonly" @click="newQuestion()">提问</el-button><router-link :to="{path:'/help',hash:teacher?'#teacher-notice':'#student-notice'}">隐私说明</router-link></div>
<p class="hint">公开区只展示教师整理的摘要和答复。原问题与追问始终仅提问人和教师可读。</p>
<div class="toolbar"><el-input v-model="keyword" placeholder="搜索问题" style="max-width:300px" @keyup.enter="page=1;load()"/><el-select v-if="tab==='private'" v-model="filter" clearable placeholder="所有状态" style="width:140px" @change="page=1;load()"><el-option label="待回复" value="open"/><el-option label="已回复" value="answered"/><el-option label="已解决" value="resolved"/></el-select><el-button @click="page=1;load()">搜索</el-button></div>
<article v-for="r in rows" :key="r.id" class="assignment-card"><template v-if="tab==='public'"><b>{{r.pinned?'置顶 · ':''}}{{r.summary}}</b><p style="white-space:pre-wrap">{{r.reply}}</p><small>{{r.created_at}} · {{r.student_name}}</small></template><template v-else><el-button link type="primary" @click="open(r)">{{r.pinned?'置顶 · ':''}}{{r.title}}</el-button><p>{{r.student_name}} · {{r.must_private?'必须私人':'允许教师另发公开摘要'}} · {{({open:'待回复',answered:'已回复',resolved:'已解决'})[r.status]}} {{r.hidden?' · 已隐藏':''}}</p></template></article>
<p v-if="!rows.length" class="hint">暂无相关问答。</p><div class="toolbar"><el-button :disabled="page===1" @click="page--;load()">上一页</el-button><span>第{{page}}页</span><el-button :disabled="rows.length<20" @click="page++;load()">下一页</el-button></div>
<el-dialog v-model="compose" :title="editId?'编辑问题':'提出私人问题'" width="min(640px,94vw)"><el-input v-model="title" placeholder="标题" maxlength="200"/><el-input v-model="content" type="textarea" :rows="6" placeholder="问题内容" style="margin:16px 0"/><el-checkbox v-if="!editId" v-model="mustPrivate">必须私人，教师不得向全班公开</el-checkbox><p class="hint">取消勾选也不会自动公开，只允许老师另写公开摘要。</p><template #footer><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
<el-dialog v-model="dialog" :title="detail?.title" width="min(760px,94vw)"><template v-if="detail"><p style="white-space:pre-wrap">{{detail.content}}</p><p class="hint">{{detail.must_private?'必须私人':'允许教师公开摘要'}} · 原帖始终私人</p><div class="toolbar"><template v-if="!teacher"><el-button :disabled="readonly&&!!detail.must_private" @click="privacy">{{detail.must_private?'允许公开摘要':'改为必须私人并撤回摘要'}}</el-button><template v-if="!readonly&&!detail.replies.length&&!detail.publications.length"><el-button @click="newQuestion(detail)">编辑</el-button><el-button type="danger" @click="remove">删除</el-button></template></template><template v-else><el-button v-if="!readonly" @click="action('/manage',{status:'resolved'},'put')">标记解决</el-button><el-button v-if="!readonly" @click="action('/manage',{pinned:!detail.pinned},'put')">{{detail.pinned?'取消置顶':'置顶'}}</el-button><el-button :disabled="readonly&&!!detail.hidden" @click="action('/manage',{hidden:!detail.hidden},'put')">{{detail.hidden?'取消隐藏':'隐藏并撤回公开'}}</el-button><el-button :disabled="!!detail.must_private||readonly||!!detail.hidden" @click="publishDialog">整理公开摘要</el-button><el-button @click="action('/withdraw')">撤回公开摘要</el-button></template></div>
<article v-for="r in detail.replies" :key="r.id" class="assignment-card"><b>{{r.author_name}} · {{r.created_at}}</b><p style="white-space:pre-wrap">{{r.content}}</p></article><template v-if="!readonly"><el-input v-model="reply" type="textarea" :rows="3" placeholder="私人回复 / 追问"/><el-button type="primary" style="margin-top:12px" @click="sendReply">发送私人回复</el-button></template><h4 v-if="detail.publications.length">公开摘要历史</h4><article v-for="p in detail.publications" :key="p.id" class="assignment-card"><b>{{p.status==='published'?'已公开':'已撤回'}} · {{p.created_at}}</b><p>{{p.summary}}</p><p>{{p.reply}}</p></article></template></el-dialog>
<el-dialog v-model="publication" title="另写公开摘要与答复" width="min(640px,94vw)"><p>请删除私人信息；公开后已被阅读的内容无法收回。</p><el-input v-model="summary" type="textarea" :rows="3" placeholder="公开问题摘要"/><el-input v-model="publicReply" type="textarea" :rows="5" placeholder="公开答复" style="margin-top:14px"/><template #footer><el-button type="primary" @click="publish">向全班公布</el-button></template></el-dialog>
</section></template>
